Repository opengisch/qgis-plugin-ci, pull requests merged in 2022-09, with the labels that each got.

#154 use concurrency to avoid multiple workflow running at once
  .github/workflows/release.yml
Labels: enhancement

#151 Fix regression in 2.4 where zip was not compressed
  qgispluginci/release.py
Labels: bug

#156 Feature: add verbosity option and improve log
  qgispluginci/changelog.py
  qgispluginci/parameters.py
  qgispluginci/release.py
  qgispluginci/translation.py
  qgispluginci/utils.py
  requirements/development.txt
  scripts/qgis_plugin_ci.py
  test/test_changelog.py
  test/test_release.py
Labels: enhancement

#158 Handle missing changelog when latest is passed
  qgispluginci/exceptions.py
  qgispluginci/release.py
Labels: enhancement

#160 Fix 159: Add missing parameters and set a default value
  qgispluginci/release.py
Labels: bug

#161 Align xmlrpc verbosity on CLI option
  qgispluginci/release.py
Labels: enhancement

#163 Complete latest releases notes to changelog
  CHANGELOG.md
Labels: documentation
