Repository opengisch/qgis-plugin-ci, pull requests merged in 2023-02, with the labels that each got.

#188 Avoid duplicated dependencies listing by loading dependencies from requirements files
  setup.py
Labels: dependencies

#189 Add 2.5.3 release notes
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#191 Modernize build and packaging to publish as wheel
  .github/workflows/release.yml
Labels: bug

#192 Documentation: modernize CI and add credits page with automatic dependencies listing
  .github/workflows/docs_builder.yml
  docs/index.md
  docs/misc/credits.md
Labels: documentation

#195 Docs/switch to furo
  .github/workflows/docs_builder.yml
  docs/conf.py
  docs/index.md
  docs/usage/cli_package.md
  docs/usage/cli_release.md
  qgispluginci/__about__.py
  requirements/documentation.txt
  setup.py
Labels: documentation

#197 Documentation: add sitemap
  docs/conf.py
  docs/robots.txt
  requirements/documentation.txt
Labels: documentation

#199 Python - Remove some last Python format functions
  setup.py
Labels: enhancement
